Resources:
  SprocketAttributeGroupScienceOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "10005"
        Active: "1"
        ParentDept: Research
        ContactAlias: science_team@spacely.com
      Name: Science_Org
      Description: Organization metadata for the Sprockets science team
      Tags:
        Dept: Dept10005
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupScience_Org
  SprocketAttributeGroupRoboticsOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "10006"
        Active: "1"
        ParentDept: Research
        ContactAlias: robotics_team@spacely.com
      Name: Robotics_Org
      Description: Organization metadata for the Sprockets robotics team
      Tags:
        Dept: Dept10006
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupRobotics_Org
  SprocketAttributeGroupColonyPlacementOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "20002"
        Active: "1"
        ParentDept: Product
        ContactAlias: colony_placement_team@spacely.com
      Name: ColonyPlacement_Org
      Description: Organization metadata for the Sprockets conoloy placement team
      Tags:
        Dept: Dept20002
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupColonyPlacement_Org
  SprocketAttributeGroupColonyServicesOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "20004"
        Active: "1"
        ParentDept: Product
        ContactAlias: colony_services_team@spacely.com
      Name: ColonyServices_Org
      Description: Organization metadata for the Sprockets conoloy services team
      Tags:
        Dept: Dept20004
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupColonyServices_Org
  SprocketAttributeGroupMarketingOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "80008"
        Active: "1"
        ParentDept: Marketing
        ContactAlias: colony_services_team@spacely.com
      Name: Marketing_Org
      Description: Organization metadata for the Sprockets marketing micro sites team for colonies
      Tags:
        Dept: Dept80008
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupMarketing_Org
  SprocketAttributeGroupCallCenterOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "80001"
        Active: "1"
        ParentDept: Marketing
        ContactAlias: colony_services_team@spacely.com
      Name: CallCenter_Org
      Description: Organization metadata for the Sprockets marketing call center team for colonies
      Tags:
        Dept: Dept80001
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupCallCenter_Org
  SprocketAttributeGroupColonyLogisticsOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "10006"
        Active: "1"
        ParentDept: Corp
        ContactAlias: colony_services_team@spacely.com
      Name: ColonyLogistics_Org
      Description: Organization metadata for the Sprockets colony logistics team for colonies
      Tags:
        Dept: Dept10006
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupColonyLogistics_Org
  SprocketAttributeGroupITOrg:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Department: "10009"
        Active: "1"
        ParentDept: Corp
        ContactAlias: colony_services_team@spacely.com
      Name: IT_Org
      Description: Organization metadata for the Sprockets IT team
      Tags:
        Dept: Dept10009
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupIT_Org
  SprocketAttributeGroupITInfraApplication:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        AppType: Processing
        SLA: 0.1h
        Runtime: Java-12
        Support:
          Phone: XXX-XXX-XXXX
          Email: support@app.com
        Compliance:
          - SOC-1
          - PCI
      Name: ITInfraApplication
      Description: Application metadata for the Sprockets IT Apps
      Tags:
        Dept: Dept10009
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupITInfraApplication
  SprocketAttributeGroupAnalyticsApplication:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        AppType: DataAnalytics
        SLA: 2.0h
        Runtime: Python
        Support:
          Phone: XXX-XXX-XXXX
          Email: support@app.com
        Compliance:
          - SOC-1
          - PCI
      Name: AnalyticsApplication
      Description: Application metadata for the Sprockets Analytics Apps
      Tags:
        Dept: Dept10009
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupAnalyticsApplication
  SprocketAttributeGroupITBudget:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        BudgetType: Allocation
        Capital: "No"
        Reporting: Weekly
        Owner: IT
      Name: ITBudget
      Description: Application metadata for IT Budget Attribution
      Tags:
        Dept: Dept10009
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupITBudget
  SprocketAttributeGroupPartnerBudget:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        PartnerName_ApplicationID: "12345"
        DashboardURL: http://partnername.com/customer-specificURL
        AverageMonthlyCost: $32.50
        AverageDailyCost: $1.00
        ProjectedMonthlyCost: $30.00
        AverageCostPerDayOfWeek:
          Monday: $0.50
          Tuesday: $0.55
          Wednesday: $0.60
          Thursday: $0.70
          Friday: $1.10
          Saturday: $1.85
          Sunday: $1.20
      Name: PartnerBudget
      Description: An attribute group that describes the budget for a particular application
      Tags:
        Dept: Dept10009
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupPartnerBudget
  SprocketAttributeGroupMarketingAnalysisApplication:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Customer_ApplicationName: MarketingAnalysisApplication
        Customer_ApplicationID: "991538"
        AppCriticality: High
        AppRTO_minutes: "5"
        AppLOB: Galactic_Marketing
        CostCenter: "42"
        LOB_Owner: Zaphod Beeblebrox
        LOB_Title: Chief Marketing Officer
        AppCodeRepo: githubURL
        OnCall:
          PrimaryName: Ford Prefect
          PrimaryPhone: 206-555-1212
          SecondaryName: Arthur Dent
          SecondaryPhone: 312-555-1212
          EscalationVP: Trillian
          EscalationPhone: 515-555-1212
      Name: MarketingAnalysisApplication
      Description: The attributes that describes the marketing analysis application
      Tags:
        Dept: Dept10009
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupMarketingAnalysisApplication
  SprocketAttributeGroupMarketingAnalysisApplicationComponents:
    Type: AWS::ServiceCatalogAppRegistry::AttributeGroup
    Properties:
      Attributes:
        Customer_ApplicationID: "12345"
        ApplicationName: amazon.com
        ApplicationDescription: My company's e-commerce site
        BusinessUnits:
          RevenueGenerating: "Yes"
          Non-RevenueGenerating: "No"
        BusinessArchitecture:
          BusinessProcesses: e-commerce
          BusinessCababilities: list here
        CustomersPartners:
          ProductLines: all
          DigitalPlatforms:
            web: "Yes"
            mobile: "Yes"
            social: "Yes"
        Solutions:
          Applications: list here
          Products: ""
          Services: Seller Marketplace, Prime
        Towers:
          EndUser: ""
          Application: ""
          Delivery: ""
          SecurityCompliance: ""
          ITManagement: ""
          DataCenter: ""
          Network: ""
          Compute: ""
          Storage: ""
          Platform: ""
          Output: ""
        CostPools:
          InternalLabor: "Yes"
          ExternalLabor: "Yes"
          OutsideServices: "Yes"
          Hardware: "Yes"
          Software: "Yes"
          FacilitiesPower: "Yes"
          Telecom: "Yes"
          Other: "Yes"
          InternalServices: "Yes"
      Name: MarketingAnalysisApplicationComponents
      Description: MarketingAnalysisApplicationAttributes
      Tags:
        Dept: Dept10009
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketAttributeGroupMarketingAnalysisApplicationComponents
  SprocketDefaultApplication:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties:
      Name: DefaultApplication
      Description: A default application for the account and region.
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketDefaultApplication
  SprocketStackAppAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application: CatalogInstaller
      Resource:
        Ref: AWS::StackId
      ResourceType: CFN_STACK
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SprocketStackAppAssociation
  SNSTopicCCOENotify:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SpacelyNotificationTopic_CCOENotify
      TopicName: CCOENotify
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SNSTopicCCOENotify
  SNSSubscriptionCCOENotify:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: email
      TopicArn:
        Ref: SNSTopicCCOENotify
      Endpoint: aws-sc-test@amazon.com
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SNSSubscriptionCCOENotify
  SNSTopicDataNotify:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: SpacelyNotificationTopic_DataNotify
      TopicName: DataNotify
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SNSTopicDataNotify
  SNSSubscriptionDataNotify:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sms
      TopicArn:
        Ref: SNSTopicDataNotify
      Endpoint: "12063996889"
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/SNSSubscriptionDataNotify
  ConfigRecorder:
    Type: AWS::Config::ConfigurationRecorder
    Properties:
      RoleARN: arn:aws:iam::133842445017:role/SpacelySprocketsConfigRole
      Name: SpacelySprocketConfigRecorder
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/ConfigRecorder
  ConfigBucket2112C5EC:
    Type: AWS::S3::Bucket
    UpdateReplacePolicy: Retain
    DeletionPolicy: Retain
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/ConfigBucket/Resource
  ConfigBucketPolicy6D5E90FF:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: ConfigBucket2112C5EC
      PolicyDocument:
        Statement:
          - Action: s3:GetObjectAcl
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::133842445017:role/SpacelySprocketsConfigRole
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - ConfigBucket2112C5EC
                      - Arn
                  - /*
          - Action: s3:PutObject
            Effect: Allow
            Principal:
              AWS: arn:aws:iam::133842445017:role/SpacelySprocketsConfigRole
            Resource:
              Fn::Join:
                - ""
                - - Fn::GetAtt:
                      - ConfigBucket2112C5EC
                      - Arn
                  - /*
        Version: "2012-10-17"
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/ConfigBucket/Policy/Resource
  ConfigDeliveryChannel:
    Type: AWS::Config::DeliveryChannel
    Properties:
      S3BucketName:
        Ref: ConfigBucket2112C5EC
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/ConfigDeliveryChannel
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAAE02P0U7DMAxFv2XvXQaa0MQbpUg8MnX8QOZ6ndcSR44zVFX9d5IUCZ58bd9zZT+a5yfzsHmx32EL3bCbgQXNfFILQ9Vc3EdUH7Vq2AWVCJpnLQaOAph1WnSkxG6pcsQcUO4ECFbtyL31XrCnhE5mTu5aVegcFd+Fo8987f1IyZ0S/kfXITCQXYODC4X+ZE+QXad4DiDk1zWwu1BfHE2RUQrYYvqlQ8nEG450R5maq3UOx5S5N/NrhAHLR79qLUdOF01/47VflqU6Tnplt9ubgzlsboFoK9EpfaFp1/oDvQeBAk4BAAA=
    Metadata:
      aws:cdk:path: SprocketsCatalogCoreInRegionStack/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Outputs:
  SNSTopicArnCCOENotify:
    Description: The ARN of the SNS Topic SpacelyNotificationTopic_CCOENotify
    Value:
      Ref: SNSTopicCCOENotify
    Export:
      Name: CCOENotify
  SNSTopicArnDataNotify:
    Description: The ARN of the SNS Topic SpacelyNotificationTopic_DataNotify
    Value:
      Ref: SNSTopicDataNotify
    Export:
      Name: DataNotify
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - af-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

