AWSTemplateFormatVersion: '2010-09-09'
Description: API Gateway Rest API
Parameters:
  APIGatewayName:
    Type: String
    Description: Provide the name of your API Gateway
  ApplicationName:
    Type: String
    Description: Provide the name of the application associated with this provisioned product
    Default: DefaultApplication
    MinLength: '1'
    MaxLength: '128'
    AllowedPattern: "([a-zA-Z0-9][a-zA-Z0-9_-]*)"
Resources:
  ApplicationAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application:
        Ref: ApplicationName
      ResourceType: CFN_STACK
      Resource:
        Ref: AWS::StackId
  apiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: !Ref 'APIGatewayName'
      Description: !Ref 'APIGatewayName'
