---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  ApplicationName:
    Type: String
    Description: Provide the name of the application associated with this provisioned product
    Default: DefaultApplication
    MinLength: '1'
    MaxLength: '128'
    AllowedPattern: "([a-zA-Z0-9][a-zA-Z0-9_-]*)"
Resources:
  ApplicationAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application:
        Ref: ApplicationName
      ResourceType: CFN_STACK
      Resource:
        Ref: AWS::StackId
  AWSConfigRulePublicIPs:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: ec2-instance-no-public-ip
      Description: Checks whether Amazon Elastic Compute Cloud (Amazon EC2) instances
        have a public IP association. The rule is NON_COMPLIANT if the publicIp field
        is present in the Amazon EC2 instance configuration item. This rule applies
        only to IPv4.
      InputParameters: {}
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_NO_PUBLIC_IP
  AWSConfigRuleDetailedMonitoringEnabled:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: ec2-instance-detailed-monitoring-enabled
      Description: Checks if detailed monitoring is enabled for EC2 instances.
        The rule is NON_COMPLIANT if detailed monitoring is not enabled.
      InputParameters: {}
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_INSTANCE_DETAILED_MONITORING_ENABLED
  AWSConfigRuleEC2StoppedInstance:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: ec2-stopped-instance-monitoring-enabled
      Description: Checks if there are instances stopped for more than
        the allowed number of days. The instance is NON_COMPLIANT if the
        state of the ec2 instance has been stopped for longer than
        the allowed number of days.
      InputParameters: {}
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: EC2_STOPPED_INSTANCE
  AWSConfigRuleCloudWatchMonitoring:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: ec2-cloud-watch-monitoring-enabled
      Description: Checks whether the specified resource type has a CloudWatch alarm
        for the specified metric. For resource type, you can specify EBS volumes,
        EC2 instances, RDS clusters, or S3 buckets.
      InputParameters: {"resourceType":"AWS::EC2::Instance","metricName":"CPUUtilization"}
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::Instance
      Source:
        Owner: AWS
        SourceIdentifier: CLOUDWATCH_ALARM_RESOURCE_CHECK
  AWSConfigRuleSecurityGroup:
    Type: AWS::Config::ConfigRule
    Properties:
      ConfigRuleName: ec2-security-group-attached-to-eni
      Description: Checks that non-default security groups are attached to Amazon Elastic Compute Cloud (EC2) instances
      InputParameters: {}
      Scope:
        ComplianceResourceTypes:
          - AWS::EC2::SecurityGroup
      Source:
        Owner: AWS
        SourceIdentifier: EC2_SECURITY_GROUP_ATTACHED_TO_ENI