---
AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB Table
Transform: AWS::ServiceCatalog
Parameters:
  TableName:
    Type: String
    Description: Provide the name of your DynamoDB table
    MinLength: 3
    MaxLength: 30
  IndexName:
    Type: String
    Description: Provide the name of the DynamoDB table index
  ApplicationName:
    Type: String
    Description: Provide the name of the application associated with this provisioned product
    Default: DefaultApplication
    MinLength: '1'
    MaxLength: '128'
    AllowedPattern: "([a-zA-Z0-9][a-zA-Z0-9_-]*)"
Resources:
  ApplicationAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application:
        Ref: ApplicationName
      ResourceType: CFN_STACK
      Resource:
        Ref: AWS::StackId
  DynamoTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref 'TableName'
      AttributeDefinitions:
        - AttributeName: !Ref IndexName
          AttributeType: "S"
      KeySchema:
        - AttributeName: !Ref 'IndexName'
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
  DynamoSuccessfulRequestLatencyAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub '${ApplicationName}-Dynamo-${TableName}-ReadCapacityAlarm'
      AlarmDescription: 'Alarm when dynamo table has latency on successful requests'
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DataNotify'
        - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:opsitem:2#CATEGORY=Availability'
      Namespace: AWS/DynamoDB
      MetricName: SuccessfulRequestLatency
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoTable
      Statistic: 'Maximum'
      Threshold: 5
      ComparisonOperator: 'GreaterThanThreshold'
      Period: 300
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
  DynamoWriteCapAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub '${ApplicationName}-Dynamo-${TableName}-WriteCapacityAlarm'
      AlarmDescription: 'Alarm when dynamo table approaches maximum write capacity limit'
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DataNotify'
        - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:opsitem:2#CATEGORY=Availability'
      Namespace: AWS/DynamoDB
      MetricName: AccountProvisionedWriteCapacityUtilization
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoTable
      Statistic: 'Maximum'
      Threshold: 20
      ComparisonOperator: 'GreaterThanThreshold'
      Period: 300
      EvaluationPeriods: 1
      TreatMissingData: breaching
  DynamoReadThrottleAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub '${ApplicationName}-Dynamo-${TableName}-ReadThrottleAlarm'
      AlarmDescription: 'Alarm when dynamo table experiences read throttle events'
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DataNotify'
        - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:opsitem:3#CATEGORY=Performance'
      Namespace: AWS/DynamoDB
      MetricName: ReadThrottleEvents
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoTable
      Statistic: 'Average'
      Threshold: 4
      ComparisonOperator: 'GreaterThanThreshold'
      Period: 300
      EvaluationPeriods: 1
      TreatMissingData: breaching
  DynamoWriteThrottleAlarm:
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmName: !Sub '${ApplicationName}-Dynamo-${TableName}-WriteThrottleAlarm'
      AlarmDescription: 'Alarm when dynamo table experiences write throttle events'
      AlarmActions:
        - !Sub 'arn:aws:sns:${AWS::Region}:${AWS::AccountId}:DataNotify'
        - !Sub 'arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:opsitem:4#CATEGORY=Performance'
      Namespace: AWS/DynamoDB
      MetricName: WriteThrottleEvents
      Dimensions:
        - Name: TableName
          Value: !Ref DynamoTable
      Statistic: 'Average'
      Threshold: 4
      ComparisonOperator: 'GreaterThanThreshold'
      Period: 300
      EvaluationPeriods: 1
      TreatMissingData: notBreaching
Outputs:
  TableName:
    Value: !Ref 'TableName'
