---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB CCOE compliant database.'
Parameters:
  TableName:
    Type: String
    Description: Provide the name of your DynamoDB table
  IndexName:
    Type: String
    Description: Provide the name of the DynamoDB table index
Resources:
  CustomerDatabase:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Ref 'TableName'
      AttributeDefinitions:
        - AttributeName: !Ref IndexName
          AttributeType: "S"
      KeySchema:
        - AttributeName: !Ref 'IndexName'
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
Outputs:
  TableName:
    Value: !Ref 'TableName'
