AWSTemplateFormatVersion: '2010-09-09'
Description: 'RDS CCOE compliant database.'
Parameters:
  RDSUserName:
    Type: String
    Description: Provide the user name of your RDS database
  RDSPassword:
    Type: String
    Description: Provide the password for your RDS database
Resources:
  MyDB:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBInstanceClass: db.t2.small
      Engine: MySQL
      MasterUsername: !Ref RDSUserName
      MasterUserPassword: !Ref RDSPassword
    DeletionPolicy: Snapshot
Outputs:
  DatabaseInstanceId:
    Value: !Ref MyDB
