---
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::ServiceCatalog
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: AWS::EC2::KeyPair::KeyName
    ConstraintDescription: Can contain only ASCII characters.
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.small
    AllowedValues:
    - t1.micro
    - t2.nano
    - t2.micro
    - t2.small
    - t2.medium
    - t2.large
    ConstraintDescription: must be a valid EC2 instance type.
  SSHLocation:
    Description: The IP address range that can be used to SSH to the EC2 instances
    Type: String
    MinLength: '9'
    MaxLength: '18'
    Default: 0.0.0.0/0
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: Must be a valid IP CIDR range of the form x.x.x.x/x
  ApplicationName:
    Type: String
    Description: Provide the name of the application
    Default: DefaultApplication
    MinLength: '1'
    MaxLength: '128'
    AllowedPattern: "([a-zA-Z0-9][a-zA-Z0-9_-]*)"
  ApplicationDescription:
    Type: String
    Description: Provide the description of the application
    MinLength: '1'
  TableName:
    Type: String
    Description: Provide the name of your DynamoDB table
    MinLength: 3
    MaxLength: 30
  IndexName:
    Type: String
    Description: Provide the name of the DynamoDB table index
  MyBucketName:
    Type: String
    Description: The name of the bucket
Resources:
  ApplicationRegistration:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties:
      Name:
        Ref: ApplicationName
      Description:
        Ref: ApplicationDescription
  ApplicationAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application:
        Ref: ApplicationName
      ResourceType: CFN_STACK
      Resource:
        Ref: AWS::StackId
  Compute:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Sprocket EC2 Server
      ProvisioningArtifactName: '1.0'
      PathName: 'Sprocket CCOE EC2 Infra'
      ProvisioningParameters:
        -
          Key: ApplicationName
          Value:
            Ref: ApplicationName
        - Key: InstanceType
          Value:
            Ref: InstanceType
        - Key: KeyName
          Value:
            Ref: KeyName
        - Key: SSHLocation
          Value:
            Ref: SSHLocation
      Tags:
        - Key: DataSecurityClassification
          Value: "High"
        - Key: Environment
          Value: "Development"
        - Key: Department
          Value: "10005"
  FileStorage:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Sprocket Private S3 Bucket
      ProvisioningArtifactName: 1.0
      PathName: 'Sprocket CCOE EC2 Infra'
      ProvisioningParameters:
        -
          Key: ApplicationName
          Value:
            Ref: ApplicationName
        -
          Key: MyBucketName
          Value:
            Ref: MyBucketName
      Tags:
        -
          Key: DataSecurityClassification
          Value: "High"
        -
          Key: Environment
          Value: "Development"
        -
          Key: Department
          Value: "10005"
  Database:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Sprocket DynamoDB
      ProvisioningArtifactName: '1.0'
      PathName: 'Sprocket CCOE Serverless Infra'
      ProvisioningParameters:
        -
          Key: ApplicationName
          Value:
            Ref: ApplicationName
        -
          Key: IndexName
          Value:
            Ref: IndexName
        - Key: TableName
          Value:
            Ref: TableName
      Tags:
        -
          Key: DataSecurityClassification
          Value: "High"
        -
          Key: Environment
          Value: "Development"
        -
          Key: Department
          Value: "10005"
  ConfigEC2:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Sprocket Config EC2 Monitoring
      ProvisioningArtifactName: '1.0'
      PathName: 'Sprocket CCOE IT Infra'
      ProvisioningParameters:
        -
          Key: ApplicationName
          Value:
            Ref: ApplicationName
      Tags:
        -
          Key: DataSecurityClassification
          Value: "High"
        -
          Key: Environment
          Value: "Development"
        -
          Key: Department
          Value: "10005"
  ConfigS3:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Sprocket Config S3 Monitoring
      ProvisioningArtifactName: '1.0'
      PathName: 'Sprocket CCOE IT Infra'
      ProvisioningParameters:
        -
          Key: ApplicationName
          Value:
            Ref: ApplicationName
      Tags:
        -
          Key: DataSecurityClassification
          Value: "High"
        -
          Key: Environment
          Value: "Development"
        -
          Key: Department
          Value: "10005"
  ConfigDynamo:
    Type: AWS::ServiceCatalog::CloudFormationProvisionedProduct
    Properties:
      ProductName: Sprocket Config Dynamo Monitoring
      ProvisioningArtifactName: '1.0'
      PathName: 'Sprocket CCOE IT Infra'
      ProvisioningParameters:
        -
          Key: ApplicationName
          Value:
            Ref: ApplicationName
      Tags:
        -
          Key: DataSecurityClassification
          Value: "High"
        -
          Key: Environment
          Value: "Development"
        -
          Key: Department
          Value: "10005"
Outputs:
  WebsiteURL:
    Description: URL for newly created EC2 stack
    Value:
      Fn::Join:
      - ''
      - - http://
        - Fn::GetAtt:
          - [Compute, Outputs.WebServerInstance]
          - [Compute, Outputs.PublicDnsName]
