Resources:
  serverlessInfa:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Sprocket CCOE Serverless Infra
      ProviderName: Spacely Sprockets CCOE
      Description: Spacely Sprocket CCOE approved serverless infrastructure building blocks and kits
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/serverlessInfa
  containersInfa:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Sprocket CCOE Container Infra
      ProviderName: Spacely Sprockets CCOE
      Description: Spacely Sprocket CCOE approved container infrastructure building blocks and kits
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/containersInfa
  ec2Infa:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Sprocket CCOE EC2 Infra
      ProviderName: Spacely Sprockets CCOE
      Description: Spacely Sprocket CCOE approved EC2 infrastructure building blocks and kits
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/ec2Infa
  scienceInfa:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Sprocket CCOE Science Infra
      ProviderName: Spacely Sprockets CCOE
      Description: Spacely Sprocket CCOE approved Science infrastructure building blocks and kits
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/scienceInfa
  ccoeitInfa:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Sprocket CCOE IT Infra
      ProviderName: Spacely Sprockets CCOE
      Description: Spacely Sprocket CCOE approved IT infrastructure building blocks and kits
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/ccoeitInfa
  SprockDynamo:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket DynamoDB
      Owner: Sprockets Database Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-dynamodb-v1.yaml
          Name: "1.0"
      Description: The Sprocket CCOE approved DynamoDB for security and compliance requirements. Supports passing in the name of the table and the name of the index
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-dynamo-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockDynamo
  SprockDynamoserverlessInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: serverlessInfa
      ProductId:
        Ref: SprockDynamo
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockDynamoserverlessInfa
  SprockDynamoscienceInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: scienceInfa
      ProductId:
        Ref: SprockDynamo
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockDynamoscienceInfa
  SprockLambdaPython:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket Lambda
      Owner: Sprockets Compute Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-lambdapython-v1.yaml
          Name: "1.0"
      Description: The Sprocket CCOE approved Lambda using Python for security and compliance requirements. Pass in the GitHub location of your Serverless code.
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-lambda-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockLambdaPython
  SprockLambdaPythonserverlessInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: serverlessInfa
      ProductId:
        Ref: SprockLambdaPython
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockLambdaPythonserverlessInfa
  SprockLambdaPythonscienceInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: scienceInfa
      ProductId:
        Ref: SprockLambdaPython
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockLambdaPythonscienceInfa
  SprockAPIGWLambda:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket API Gateway for Lambda
      Owner: Sprockets Severless Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-apigateway-v1.yaml
          Name: "1.0"
      Description: The Sprocket CCOE approved Lambda API Gateway for security and compliance requirements. The API Gateway connects to a Sprocket Lambda and provides an addressable URL
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-apigw-lambda-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockAPIGWLambda
  SprockAPIGWLambdaserverlessInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: serverlessInfa
      ProductId:
        Ref: SprockAPIGWLambda
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockAPIGWLambdaserverlessInfa
  SprockAPIGWLambdaccoeitInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ccoeitInfa
      ProductId:
        Ref: SprockAPIGWLambda
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockAPIGWLambdaccoeitInfa
  SprockEMR:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket Elastic Map Reduce
      Owner: Sprockets Compute Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-emr-v1.yaml
          Name: "1.0"
      Description: The Sprocket EMR CCOE approved for security and compliance requirements. The EMR cluster accepts the cluster name and key as parameters and runs on an mx3 xlarge ec2.
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-emr-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockEMR
  SprockEMRec2Infa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ec2Infa
      ProductId:
        Ref: SprockEMR
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockEMRec2Infa
  SprockEMRscienceInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: scienceInfa
      ProductId:
        Ref: SprockEMR
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockEMRscienceInfa
  SprockEMRccoeitInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ccoeitInfa
      ProductId:
        Ref: SprockEMR
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockEMRccoeitInfa
  SprockIAMRoleSagemaker:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket IAM Role for Sagemaker
      Owner: Sprockets IT Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-iam-role-sagemaker-v1.yaml
          Name: "1.0"
      Description: The Sprocket Sagemaker IAM role is CCOE approved for security and compliance requirements. The IAM role grants the minimum necessary permissions for executing Sagemaker.
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-lamp-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockIAMRoleSagemaker
  SprockIAMRoleSagemakerccoeitInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ccoeitInfa
      ProductId:
        Ref: SprockIAMRoleSagemaker
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockIAMRoleSagemakerccoeitInfa
  SprockIAMRoleSagemakerscienceInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: scienceInfa
      ProductId:
        Ref: SprockIAMRoleSagemaker
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockIAMRoleSagemakerscienceInfa
  SprockLamp:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket Lamp Server
      Owner: Sprockets IT Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-lamp-v1.yaml
          Name: "1.0"
      Description: The Sprocket Lamp Server is CCOE approved for security and compliance requirements. Create a LAMP stack using a single EC2 instance and a local MySQL database for storage. This installs the packages and files necessary to deploy the Apache web server, PHP, and MySQL.
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-lamp-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockLamp
  SprockLampec2Infa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ec2Infa
      ProductId:
        Ref: SprockLamp
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockLampec2Infa
  SprockRDS:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket RDS
      Owner: Sprockets IT Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-rds-v1.yaml
          Name: "1.0"
      Description: The Sprocket RDS database is CCOE approved for security and compliance requirements. The RDS database accepts username and password as parameters.
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-rds-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockRDS
  SprockRDSec2Infa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ec2Infa
      ProductId:
        Ref: SprockRDS
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockRDSec2Infa
  SprockPrivateS3:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket Private S3 Bucket
      Owner: Sprockets IT Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-s3-v1.yaml
          Name: "1.0"
      Description: The Sprocket Private S3 Bucket is CCOE approved for security and compliance requirements. The S3 bucket accepts the name of the bucket as a parameter.
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-s3-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockPrivateS3
  SprockPrivateS3ec2Infa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ec2Infa
      ProductId:
        Ref: SprockPrivateS3
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockPrivateS3ec2Infa
  SprockPrivateS3scienceInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: scienceInfa
      ProductId:
        Ref: SprockPrivateS3
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockPrivateS3scienceInfa
  SprockPrivateS3serverlessInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: serverlessInfa
      ProductId:
        Ref: SprockPrivateS3
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockPrivateS3serverlessInfa
  SprockSageMaker:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Sprocket SageMaker Notebook
      Owner: Sprockets Science Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sc-sagemaker-v1.yaml
          Name: "1.0"
      Description: The Sprocket Sagemaker Notebook is CCOE approved for security and compliance requirements. An Amazon SageMaker notebook instance is a machine learning (ML) compute instance running the Jupyter Notebook App. SageMaker manages creating the instance and related resources. Use Jupyter notebooks in your notebook instance to prepare and process data, write code to train models, deploy models to SageMaker hosting, and test or validate your models.
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-sagemaker-details.html
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockSageMaker
  SprockSageMakerec2Infa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: ec2Infa
      ProductId:
        Ref: SprockSageMaker
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockSageMakerec2Infa
  SprockSageMakerscienceInfa:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: scienceInfa
      ProductId:
        Ref: SprockSageMaker
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/SprockSageMakerscienceInfa
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Modules: aws-cdk=1.86.0,@aws-cdk/aws-iam=1.86.0,@aws-cdk/aws-servicecatalog=1.86.0,@aws-cdk/cloud-assembly-schema=1.86.0,@aws-cdk/core=1.86.0,@aws-cdk/cx-api=1.86.0,@aws-cdk/region-info=1.86.0,jsii-runtime=Python/3.7.7
    Metadata:
      aws:cdk:path: sprockets-catalog-builder/CDKMetadata/Default
    Condition: CDKMetadataAvailable
Conditions:
  CDKMetadataAvailable:
    Fn::Or:
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-northeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-1
          - Fn::Equals:
              - Ref: AWS::Region
              - ap-southeast-2
          - Fn::Equals:
              - Ref: AWS::Region
              - ca-central-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - cn-northwest-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-central-1
      - Fn::Or:
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-north-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-2
          - Fn::Equals:
              - Ref: AWS::Region
              - eu-west-3
          - Fn::Equals:
              - Ref: AWS::Region
              - me-south-1
          - Fn::Equals:
              - Ref: AWS::Region
              - sa-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-east-2
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-1
          - Fn::Equals:
              - Ref: AWS::Region
              - us-west-2

