---
AWSTemplateFormatVersion: '2010-09-09'
Description: Installs the infrastructure required for the Spacely Sprockets Service Catalog in your hub region.
Resources:
  ProductCrossRegionInstaller:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Catalog Cross-Region Installer
      Description: Builds the cross-region catalog infrastructure which include; IAM users, groups, and roles, required for the catalog.
      Owner: Sprockets CCOE Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sprockets_catalog_core_cross_region_template.yaml
          Name: "1.0"
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-cross-region-installer-details.html
  ProductInRegionInstaller:
    Type: AWS::ServiceCatalog::CloudFormationProduct
    Properties:
      Name: Catalog In-Region Installer
      Description: Builds the in-region catalog infrastructure which include; SNS topics, config recorder, attribute groups, and a default application.
      Owner: Sprockets CCOE Team
      ProvisioningArtifactParameters:
        - Description: Initial version
          Info:
            LoadTemplateFromURL: https://raw.githubusercontent.com/edmahlum/ccoe-sc-templates/main/sprockets_catalog_core_in_region_template.yaml
          Name: "1.0"
      Distributor: Spacely Sprockets CCOE
      ReplaceProvisioningArtifacts: true
      SupportDescription: For support please use the Spacely Sprocket CCOE slack channel 8AM - 5PM earth time or for urgent issues refer to spacely-on-call
      SupportEmail: spacely_ccoe_support@spacelysprockets.com
      SupportUrl: http://intranet.spacely-sprockets.com/catalog/ccoe-in-region-installer-details.html
  PortfolioCatalogInfrastructure:
    Type: AWS::ServiceCatalog::Portfolio
    Properties:
      DisplayName: Sprocket Catalog Infatructure
      ProviderName: Spacely Sprockets CCOE
      Description: Products that build the cross-region and in-region catalog infrastructure for the account
  PortfolioPrincipalAssociationgroupAdminRoleCatalogInfrastructure:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PortfolioId:
        Ref: PortfolioCatalogInfrastructure
      PrincipalARN:
        Fn::Join:
          - ""
          - - "arn:"
            - Ref: AWS::Partition
            - ":iam::"
            - Ref: AWS::AccountId
            - :role/admin
  ProductPortfolioAssociationCrossRegionInstallerCatalogInfrastructure:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: PortfolioCatalogInfrastructure
      ProductId:
        Ref: ProductCrossRegionInstaller
  ProductPortfolioAssociationInRegionInstallerCatalogInfrastructure:
    Type: AWS::ServiceCatalog::PortfolioProductAssociation
    Properties:
      PortfolioId:
        Ref: PortfolioCatalogInfrastructure
      ProductId:
        Ref: ProductInRegionInstaller
  ApplicationCatalogInstaller:
    Type: AWS::ServiceCatalogAppRegistry::Application
    Properties:
      Name: CatalogInstaller
      Description: The application that installs the Spacely Sprocket Service Catalog.
  ApplicationResourceAssociation:
    Type: AWS::ServiceCatalogAppRegistry::ResourceAssociation
    Properties:
      Application:
        Ref: ApplicationCatalogInstaller
      Resource:
        Ref: AWS::StackId
      ResourceType: CFN_STACK